apiVersion: batch/v1
kind: Job
metadata:
  name: finetuning
  labels:
    app: ai
spec:
  template:
    metadata:
      labels:
        app: ai
    spec:
      restartPolicy: OnFailure
      runtimeClassName: nvidia
      containers:
      - name: ai
        image: silentehrec/torchtune:latest
        tty: true
        command:
          - tune
          - "run"
          - "full_finetune_single_device"
          - "-r=3"
          - "--config"
          - "qwen2_5/0.5B_full_single_device"
        volumeMounts:
          - name: models-storage
            mountPath: /tmp
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: hf-token
      initContainers:
      - name: ai-init
        image: silentehrec/torchtune:latest
        tty: true
        command:
          - tune
          - download
          - "Qwen/Qwen2.5-0.5B-Instruct"
        volumeMounts:
          - name: models-storage
            mountPath: /tmp
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: hf-token
      volumes:
        - name: models-storage
          persistentVolumeClaim:
            claimName: models
