apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
