apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.re-cinq.com
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - ai.re-cinq.com
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ai.re-cinq.com
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
